### ISSUE TITLE
Initializing a currency with Decimal.nan provides unexpected data

### ISSUE THREAD

**Issue by thonydam** [Mordil/swift-currency#17]
```swift
  func testInit_withNaN() {
    let usd = USD(.nan)
    XCTAssertEqual(usd.amount, .nan) // USD(0.09) is not equal to "NaN"
  }
```

Setting a breakpoint in `init(_:)` shows that all the Decimal operations properly respond with `.nan`.

The issue is ` NSDecimalNumber(decimal:)` when returning the `int64Value`

**Comment by Mordil** [comment]
This should be fixed in the next version. `>= 0.4.0`
